### ISSUE TITLE
RAMP: Package management / install / import

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#105]
It would be a breaking API change but I would be happy to change the import naming.

Each time that we create a new package (e.g., `ramp-utils`), we finish up by importing with a terrible naming `import ramputils`, `import ramp_utils`, `import ramputl`. It would be much better to be able to import any of the package with `import ramp.xxx` (e.g., `from ramp.sdk import xxx`, `from ramp.utils import read_config`. It would be much more intuitive.

This is open to discussion :)

**Comment by glemaitre** [comment]
The solution here is to be able to do like in `dask`.

Create a `ramp` folder in the root folder and create submodule `database`, `engine`, `utils`, etc. and import the module from there. We can warn if the subpackage is not installed moreover.

We can propose also something similar to dask for the install.
`conda install ramp[sdk]`, etc.

**Comment by kegl** [comment]
ok

**Comment by glemaitre** [comment]
Solved in #142
