### ISSUE TITLE
DATABASE: refactor rampdb.tools

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#107]
The current code organisation in `rampdb.tools` is suboptimal. While it is interested to have `query` to simplify the code, I think that we should split the `api` into specific packages. The `tools` module is also a bit mysterious for the moment.

**Comment by kegl** [comment]
Can you be more specific pls. I simply collected all scripts querying and writing into the DB into a file. What would be a better way to organize this?

**Comment by glemaitre** [comment]
You can check the PR.

Basically organize the tools to deal with submission, event, team, user, etc.
So I organized them in different modules.

**Comment by kegl** [comment]
OK.
