### ISSUE TITLE
RAMP: Updates to the configuration files

### ISSUE THREAD

**Issue by jorisvandenbossche** [paris-saclay-cds/ramp-board#121]
- [x] Make sure the code works with splitted config + update tests: one config.yml for flask + sqlalchemy information, and one config.yml for ramp and worker information (located in an event-specific directory)
- [x] Use full path to the kit directory and data directory (the database fields) instead of the kit**s** dir that needs to be combined with the problem name
- [x] Config file (ramp): remove 'deployment_dir', and make 'data_dir', 'kits_dir', 'submissions_dir' into full absolute paths
- [x] Config file (ramp): set the defaults for  'data_dir', 'kits_dir', 'submissions_dir', 'predictions_dir' and 'logs_dir' such that for current server we don't need to have those in a minimal config file ('data_dir', 'kits_dir', 'submissions_dir' can use default name relative to config.yml location, and  'predictions_dir' and 'logs_dir' similar but relative to the event's config.yml)
- [x] Change 'event' to 'problem_name' in the ramp config part

**Comment by glemaitre** [comment]
Thinking about it, I think that we could split into three configurations:

* flask alone
* database alone
* ramp alone

**Comment by jorisvandenbossche** [comment]
Do we already have tests for the defaults?

**Comment by glemaitre** [comment]
I made an integration tests which uses the defaults. It was the easiest things that I could come with. Il also check the way the defaults are generated (however this is just a unit tests for the utile generator config)
                                                                                                                                      
 

                            
     

Sent from my phone - sorry to be brief and potential misspell.
