### ISSUE TITLE
Submission error messages not displayed in  training_error

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#179]
Currently, users can't seem to see the error in their submission. For instance,

for the failed run http://ramp.r0h.eu:8080/b14a4b62ab7e3eb3322f098d80ab5b03ebddb6bb/error.txt, the ` training_error` is,
```py
    /home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/site-packages/pyarrow/pandas_compat.py:708: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
      labels = getattr(columns, 'labels', None) or [
    /home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/site-packages/pyarrow/pandas_compat.py:735: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
      return pd.MultiIndex(levels=new_levels, labels=labels, names=columns.names)
    /home/rth/miniconda3/envs/ramp-solar-wind/lib/python3.7/site-packages/pyarrow/pandas_compat.py:752: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
      labels, = index.labels
```
while the actual error in `log/submission_000000023/log` is
```py
Traceback (most recent call last):

  File "/home/rth/src/ramp-workflow/rampwf/utils/submission.py", line 111, in train_test_submission
    trained_workflow, X_train)

  File "/home/rth/ramp_deployment2/ramp-kits/solar_wind/problem.py", line 54, in test_submission
    y_proba = self.classifier_workflow.test_submission(clf, X_test_array)

  File "/home/rth/src/ramp-workflow/rampwf/workflows/classifier.py", line 19, in test_submission
    y_proba = clf.predict_proba(X_array)

AttributeError: 'Classifier' object has no attribute 'predict_proba'
```

I am aware there is some traceback obfuscation code but this makes it very difficult for users to understand what went wrong.

https://github.com/paris-saclay-cds/ramp-board/pull/169 is another topic, right?

**Comment by jorisvandenbossche** [comment]
OK, the reason is: we store both the stderr as the output captured by the subprocess in the log file:

https://github.com/paris-saclay-cds/ramp-board/blob/dc3335ded32b410f8680c1ea1bd97923c999d6bf/ramp-engine/ramp_engine/local.py#L143-L151

but then from that method only return stderr, which is what gets stored in the database. So we need to concatenate both in memory as well to return from that method.

**Comment by jorisvandenbossche** [comment]
Can you try this?

```patch
--- a/ramp-engine/ramp_engine/local.py
+++ b/ramp-engine/ramp_engine/local.py
@@ -142,13 +142,13 @@ class CondaEnvWorker(BaseWorker):
             # communicate() will wait for the process to be completed
             self._proc_log, stderr = self._proc.communicate()
             # write the log into the disk
+            log_content = self._proc_log + b'\n\n' + stderr
             log_dir = os.path.join(self.config['logs_dir'],
                                    self.submission)
             if not os.path.exists(log_dir):
                 os.makedirs(log_dir)
             with open(os.path.join(log_dir, 'log'), 'wb+') as f:
-                f.write(self._proc_log)
-                f.write(stderr)
+                f.write(log_content)
             # copy the predictions into the disk
             # no need to create the directory, it will be handle by copytree
             pred_dir = os.path.join(self.config['predictions_dir'],
@@ -161,4 +161,4 @@ class CondaEnvWorker(BaseWorker):
             shutil.copytree(output_training_dir, pred_dir)
             self.status = 'collected'
             logger.info(repr(self))
-            return (self._proc.returncode, stderr.decode('utf-8'))
+            return (self._proc.returncode, log_content.decode('utf-8'))
```

**Comment by rth** [comment]
Thanks a lot @jorisvandenbossche !

I would rather not test this on solar_wind problem (which is the only event currently deployed on the server) as one run takes 20 min. Will try to write a test case for it.

**Comment by jorisvandenbossche** [comment]
I can write a test for it, no problem (we are already testing the dispatcher, I can add a submission that fails and check the log output.

**Comment by rth** [comment]
If you can that would be great (as I won't be able to look into it before this weekend). Thanks again Joris !

**Comment by jorisvandenbossche** [comment]
BTW, the code was actually correct (towards users, we only want to show the stderr (the traceback), and not the output of train_test_submission, as that contains the test scores as well.

But so that means that the bug is actually not in the dispatcher (I added a test that the dispatcher correctly stores the error traceback in the database, which was already passing on master), but in the frontend something is going wrong displaying this.

**Comment by jorisvandenbossche** [comment]
PR for just the test on the dispatcher side that things are working correctly: https://github.com/paris-saclay-cds/ramp-board/pull/182

@rth apparently we have a test that checks that the error message is in the raw html of the page that shows the error. Can you check for a case for you the source of that page and check if there is a error message in there? (maybe something goes wrong with displaying it)

**Comment by jorisvandenbossche** [comment]
Further investigation results: on our local laptops, error tracebacks are send to stderr, which is what is shown on the page on the frontend. But, on your server (and also on Amazon, we noticed yesterday), the error traceback is send to stdout, which we only store in the log, and don't show in error message on the frontend.

**Comment by rth** [comment]
> on our local laptops, error tracebacks are send to stderr

Why this separation between stderr / stdout and not merge both and store that?

> Can you check for a case for you the source of that page and check if there is a error message in there?

Given your previous message is it still useful that I check? (Can do it tomorrow)

> On our local laptops, error tracebacks are send to stderr, which is what is shown on the page on the frontend. But, on your server (and also on Amazon, we noticed yesterday), the error traceback is send to stdout,

 Just checked in a Ubuntu 18.10 VM inside a screen session (same conditions as on the server) and exceptions in a regular python script are sent to stderr. It's strange that they sent to stdout (or that there is a difference).

**Comment by jorisvandenbossche** [comment]
> Why this separation between stderr / stdout and not merge both and store that?

Because we can't show the output of train_test_submission on the private data to participants: it contains the private test score.

**Comment by jorisvandenbossche** [comment]
How the Amazon worker does this is: merge both stdout and stderr, and then extract a traceback from that to store as error message in the database. 
So if we don't figure out why the difference in errors being sent to stdout vs stderr, we can use the same approach for the conda worker as well, and then it will work regardless wether the traceback is sent to stdout or stderr.

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/paris-saclay-cds/ramp-board/pull/182
