### ISSUE TITLE
Discrepancy between the train time and evaluation time

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#193]
The training times shown on RAMP don't seem to be consistent with the evaluation time.

For instance, for the solar_wind problem, the starting kit says that the train time is 0.54 s (and test is 0.17 s), while to evaluate that submission it takes ~25min on the same server.

The evaluation time is consistent with what I get by running the `ramp_test_submission` locally, and the reported train/test time is faster by 3000x  which doesn't make sense even allowing for multiple CV folds.

**Comment by rth** [comment]
As a side note, @glemaitre  don't you think that having a "Frontend" etc. labels would be easier to manage that renaming each issue :)

**Comment by glemaitre** [comment]
I feel stupid now :) I like only to use 10% of GitHub ;)
I will create those.

**Comment by glemaitre** [comment]
Be aware that the reported time for training is only on a single fold. So you need to multiply by the number of folds. However, x3000 seems kinda of unlikely :)

**Comment by kegl** [comment]
You also need to score which is slow sometimes.

**Comment by glemaitre** [comment]
Uhm we solve this issue. We were reporting the validation time instead of the training time.
