### ISSUE TITLE
submission missing

### ISSUE THREAD

**Issue by kegl** [paris-saclay-cds/ramp-board#2]
With automated training sometimes the training job wants to start before files are copied. Should go away when we put the submissions in the db.

**Comment by glemaitre** [comment]
I am not sure that it will be still valid. It would mean that we should actually have a submission status which is `initialized` before the `new` status`. Like this it will avoid the dispatcher to pick them up. `make_submission_copy_files` should change the status from `initialized` to `new`.

**Comment by kegl** [comment]
Yes, something like that solution would help. The problem is the delay bw setting the submission state in the DB to new and physically copying uploaded files. As I said above, adding the uploaded files to the DB would solve this issue since the transaction would not terminate before those files are safely in the DB.

**Comment by kegl** [comment]
ALso note that in practice this happens rarely, only with big files, eg in air passengers, and a very reactive backend engine (which can happen with the new dispatcher).

**Comment by glemaitre** [comment]
This solved now. The copying happens in `add_submission` and we solve the issue of updating the leaderboard.
