### ISSUE TITLE
Fix CLI worker 

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#201]
The call to the CLI to launch a worker is not good right now.
We need to decide if we should pass the information with some config files or all the parameters by hand or a mix of them.

**Comment by jorisvandenbossche** [comment]
Can you clarify this issue a bit? Are you talking about the `ramp-launch worker` command?

**Comment by glemaitre** [comment]
yes exactly the command `ramp launch worker`. The worker should be agnostic to the database so we should not have to pass the database config. Before my PR, we were taking the event config to get the different required path. However, now the path could be generated with defaults and are not given in the event config. Thus, it seems that the right thing to do is to pass all the different parameter directly

**Comment by jorisvandenbossche** [comment]
OK, I understand. It would be a bit annoying to have to pass everything, but on the other hand, I don't really use it manually, so don't care that much.
