### ISSUE TITLE
Follow-up of #190 - Memory efficient request

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#226]
The following pattern would keep weakref of  `SubmissionOnCVFold` which will load into memory the prediction arrays.

```python
submissions = [get_submission_by_id(session, sub[o])
               for sub in get_submissions(session, 'iris_test', state='scored')]
for sub in submissions:
    for cv_fold in sub.on_cv_folds:
        ... # for instance get_scores, get_time, etc.
```

If submissions contains submissions then, the predictions arrays will be kept. We allievate the issue with #221 by avoiding to have `submissions` in memory and the arrays for all submissions.

However, there is a better job to be done. Getting the score, time, or memory info should not require to load the array. In facts, these info are stored in `SubmissionScoreOnCVFold`. Therefore, we could make a memory/speed efficient query avoiding to load the arrays:

```python
    submission = get_submission_by_id(session, submission_id)
    results = defaultdict(list)
    for fold_id, cv_fold in enumerate(submission.on_cv_fold):
        results['fold'].append(fold_id)
        for step in ('train', 'valid', 'test'):
            results[step].append(getattr(cv_fold, '{}_time'.format(step)))
    return pd.DataFrame(results).set_index('fold')
```

```python
for step in ('train', 'valid', 'test'):
    times_per_fold = session.query(getattr(SubmissionOnCVFold, '{}_time')).filter(SubmissionOnCVFold.submission_id == submission_id).all()
    for fold_id, times in enumerate(times_per_fold):
        results['fold'].append(fold_id)
        results[step].append(times)
    return pd.DataFrame(results).set_index('fold')
```

**Comment by kegl** [comment]
I tried this:
```
    results = defaultdict(list)
    for step in ('train', 'valid', 'test'):
        times_per_fold = session.query(
            getattr(SubmissionOnCVFold, '{}_time'.format(step))).filter(
            SubmissionOnCVFold.submission_id == submission_id).all()
        for fold_id, times in enumerate(times_per_fold):
            results['fold'].append(fold_id)
            results[step].append(times)
    return pd.DataFrame(results).set_index('fold')    
```

The return statement throws a `ValueError("arrays must all be same length")`

**Comment by kegl** [comment]
OK, done. The get_time was easy, get_scores not so much. Both work lightning fast now. https://github.com/paris-saclay-cds/ramp-board/pull/276/commits/c42d7ebc3f7dc59d18918f27a5a5be526e7e509c

**Comment by rth** [comment]
> The following pattern would keep weakref of SubmissionOnCVFold which will load into memory the prediction arrays.

I'm not sure I understood the underlying issue correctly, but isn't this related to the fact that we want to specify (or exclude) columns when querying, including for foreign keys? If so wouldn't using sqlachemy [deferred option](https://docs.sqlalchemy.org/en/13/orm/loading_columns.html#load-only-and-wildcard-options) help?

We could also add delayed in the model definition for all large sized fields. I don't think it affects the DB, it must be a sqlalchemy thing.

**Comment by glemaitre** [comment]
Actually it looks like `defer` is what we want. Let me check if it would work. I am not sure it will be good enough because we are dealing with backref which give a list on which we will iterate. But let see.

**Comment by glemaitre** [comment]
It works perfectly:

```python
    all_cv_folds = (session.query(SubmissionOnCVFold)
                           .filter_by(submission_id=submission_id)
                           .options(defer("full_train_y_pred"),
                                    defer("test_y_pred"))
                           .all())
    for fold_id, cv_fold in enumerate(all_cv_folds):
```

I spent to much time doing useless stuff, a pity that I don't know anything about ORM :)

**Comment by glemaitre** [comment]
@rth thanks

**Comment by rth** [comment]
Gread that it works. No  -- it's that sqlalchemy adds a lot of complex instructions on top of "SELECT columns from table"..
