### ISSUE TITLE
Make emails and usernames validation case insensitive

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#234]
Currently when a user signs up the system checks that such user and email doesn't already exist.

However, now this check is case sensitive, so it's enough to enter the email with one letter capitalized for it to get accepted (and same for the username).

IMO it would be better to make this validation check case insensitive.

For instance, I saw a user create multiple accounts with same username / email but different capitalization (I assume because he didn't manage to sign up with the first one that was pending approval)  which was somewhat confusing.

**Comment by glemaitre** [comment]
Good catch

**Comment by glemaitre** [comment]
I think that we can make the email case insensitive. Regarding the username, to be back compatible, I think that it will be difficult. The checking is currently done by the database itself.

**Comment by glemaitre** [comment]
Having case insensitive for email + email confirmation should be enough. We don't have the email confirmation which mean that a user can put whatever there and still get an account.
