### ISSUE TITLE
submission code should not be clickable when event is in close phase

### ISSUE THREAD

**Issue by agramfort** [paris-saclay-cds/ramp-board#273]
currently you can always click but you get an error if it's not your submission

**Comment by kegl** [comment]
Are you sure it's happening with plain users (not site admins)? On ramp.studio for sure there is no link in the closed phase: we generated two separate leaderboards (with and without links) and choose depending on the user and the phase.

**Comment by kegl** [comment]
I just checked: plain users don't see a link before public opening timestamp.

**Comment by agramfort** [comment]
it's a bug in the leaderboard when event is public.

**Comment by glemaitre** [comment]
I think that we fixed this
