### ISSUE TITLE
display submission state in my_submissions view

### ISSUE THREAD

**Issue by kegl** [paris-saclay-cds/ramp-board#277]
Most students complain about lack of info about submission after submitting it. It would be rather easy to add a "state" column in the "New submissions (pending training)" table, so at least they get the detailed state if they refresh the page.

**Comment by rth** [comment]
+1 This would improve user experience significantly IMO. A bonus would be to show the position of the submission in the queue when it hasn't started yet.

**Comment by glemaitre** [comment]
While it is easy to add the state, it will be more difficult to give right away a position in the queue.
We would need to add a new column in the Submission table where we would update the position and then the frontend would get the information from there.

So it would change the database schematic.

**Comment by glemaitre** [comment]
Note that the migration should be easy because we could initialize to -1 and we only need the position when the state == send_to_training

**Comment by agramfort** [comment]
no objection

>

**Comment by glemaitre** [comment]
I added the feature in #366 but it requires a migration.

**Comment by tomMoral** [comment]
It seems that this issue could be closed? working this way on the ramp server I believe.
