### ISSUE TITLE
logged in with someone else account

### ISSUE THREAD

**Issue by albertcthomas** [paris-saclay-cds/ramp-board#283]
When going on the server website, sometimes you are automatically logged in as someone else.

**Comment by agramfort** [comment]
I have so far never seen this

>

**Comment by kegl** [comment]
Happened to me too. On my phone in Chrome I went to the site and I was logged in as Albert, without asking for pwd. It seems it only happens among site admins. It's also not easy to reproduce this. It may be related to this: https://stackoverflow.com/questions/32885710/flask-login-sometimes-mixes-logins-im-logged-in-as-somebody-else

**Comment by glemaitre** [comment]
I think that we need to report this upstream instead to try fixing it here.
