### ISSUE TITLE
Some workers hang when stderr is too long

### ISSUE THREAD

**Issue by tomMoral** [paris-saclay-cds/ramp-board#287]
When some jobs trow a lot of warnings, this flood the stderr pipe and the job cannot return at the end. To solve this, the dispatcher should redirect stdout and stderr directly in files on the disk.

**Comment by kegl** [comment]
Yes, this happened to us too, we had no idea what was going on, thanks @tomMoral.

**Comment by rth** [comment]
So by default, `Popen` [uses `buffsize=-1`](https://docs.python.org/3.8/library/subprocess.html#subprocess.Popen) for stderr/stdout pipes which uses  `io.DEFAULT_BUFFER_SIZE` that is `8 kB` on my server. That's not much (100 lines of 80 char with ascii text) and increasing it by a factor of 10 or so be enough to fix most problems?

Combined with applying a timeout to [`Popen.communicate`](https://docs.python.org/3.8/library/subprocess.html#subprocess.Popen) to prevent someone e.g. to print the full dataset in stout this could be a solution. 

Otherwise piping directly to disk means that if someone want's to pass 1GB of data via stderr they will be able to.

WDYT @tomMoral ?

**Comment by rth** [comment]
> Combined with applying a timeout to Popen.communicate to prevent someone e.g. to print the full dataset in stdout this could be a solution.

Although, no. As far as I understand, workers hang in this case, because the stdout/stderr pipe gets full, while the process is running, so it goes to sleep mode, but the pipe is never collected  since `worker.status == "running"` ([here](https://github.com/paris-saclay-cds/ramp-board/blob/4bc503b350343f6f34617b28d8e96e06c534cdc5/ramp-engine/ramp_engine/dispatcher.py#L156)). So timeout on `communicate` won't help. Maybe then,
 -  increase the buffer even more to a few GB
 - when collecting, check the size of the stream and discard it with an error if it's larger than a few 100kb.
That would still leave people who could hand a process by sending plenty of data to stderr, but at least it won't crash the server (as a unlimited buffer size in memory or on disk could) and  those processes should be killed by the default worker timeout eventually https://github.com/paris-saclay-cds/ramp-board/pull/296

**Comment by tomMoral** [comment]
A reproducing test:

```python
import time
import subprocess
p  = subprocess.Popen(["python", "./sub_process.py"], stdout=subprocess.PIPE,
                      bufsize=-1)

while p.poll() is None:
    time.sleep(1)
    with open('log') as f:
        print("subprocess is writing line", f.readline(), end='')

stdout, stderr = p.communicate()
```

with `sub_process.py` being:
```python
for i in range(int(1e4)):
    print(i, "a" * 99)
    with open("log", "w") as f:
        f.write(f"{i}\n")
```

For my system, this hangs in line 552:
```
$ python main.py 
subprocess is writing line 552
subprocess is writing line 552
subprocess is writing line 552
subprocess is writing line 552
subprocess is writing line 552
^CTraceback (most recent call last):
  File "./sub_process.py", line 3, in <module>
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(i, "a" * 99)
KeyboardInterrupt
    time.sleep(1)
KeyboardInterrupt
```

I think the best solution is to simply use a file directly to write stdout and stderr, as this will allow for more control (we will be able to see the output directly in the log file if a job seems stuck). To me, we should chose the simplest solution regarless of "security" as this is a separate matter.

**Comment by rth** [comment]
Thanks for the reproducible example!

> To me, we should chose the simplest solution regarless of "security" as this is a separate matter.

I think, the simplest solution would be to increase the buffer size which should address most of the use cases. I agree that the risk of introducing unbuffered pipes is not very high, and that seeing the log in real time would have been nice.

Still if we want to prevent users from printing datasets to stderr (which happened in the past) we have to check its size be it in a file or in memory.

Also I am running RAMP on an oldish server with an HDD, it's already not too fast, and I don't think adding `n_workers` parallel non sequential disk writes in addition to the DB is a good thing.  Generally the current situation of storing state between the DB and the disk is not very ideal, and adding more state to the disk is not a long term solution IMO.

**Comment by tomMoral** [comment]
The process is not supposed to print anything so I am not really worried about slow disk access.

The main issue with the buffer size solution is that we do not solve the problem, we only push it farther away. It means that it is easy to deadlock the server by simply submitting multiple submission that will do a lot of printing. I find the solution of dumping the log in the file more convenient and allow to be sure that the workers will always return. Moreover, the main process dump the log to the disk anyway so it should not increase that much the need for I/O.

**Comment by rth** [comment]
> The process is not supposed to print anything so I am not really worried about slow disk access.

Logs do capture the output of `train_test_submission` (one line per evaluation fold and metric) even if it's not shown to user a few KB each, I think,
```
$ ls -lh events/air_passengers_dsb2019/logs/submission_000000*/* | tail
-rw-rw-r-- 1 ubuntu ubuntu 4.1K Dec  4 23:29 events/air_passengers_dsb2019/logs/submission_000000645/log
-rw-rw-r-- 1 ubuntu ubuntu 4.1K Dec  4 23:29 events/air_passengers_dsb2019/logs/submission_000000646/log
-rw-rw-r-- 1 ubuntu ubuntu 7.6K Dec  5 00:17 events/air_passengers_dsb2019/logs/submission_000000647/log
-rw-rw-r-- 1 ubuntu ubuntu 3.7K Dec  5 01:02 events/air_passengers_dsb2019/logs/submission_000000653/log
-rw-rw-r-- 1 ubuntu ubuntu  12K Dec  5 03:33 events/air_passengers_dsb2019/logs/submission_000000661/log
-rw-rw-r-- 1 ubuntu ubuntu 6.1K Dec  5 01:34 events/air_passengers_dsb2019/logs/submission_000000662/log
-rw-rw-r-- 1 ubuntu ubuntu 4.1K Dec  5 00:38 events/air_passengers_dsb2019/logs/submission_000000663/log
-rw-rw-r-- 1 ubuntu ubuntu 4.1K Dec  5 00:38 events/air_passengers_dsb2019/logs/submission_000000664/log
-rw-rw-r-- 1 ubuntu ubuntu 4.1K Dec  5 00:38 events/air_passengers_dsb2019/logs/submission_000000669/log
-rw-rw-r-- 1 ubuntu ubuntu 4.1K Dec  5 08:33 events/air_passengers_dsb2019/logs/submission_000000670/log
$ head events/air_passengers_dsb2019/logs/submission_000000670/log
Testing Number of air passengers prediction
Reading train and test files from /home/ubuntu/ramp_deployment/ramp-data/air_passengers/data ...
Reading cv ...
Training /home/ubuntu/ramp_deployment/events/air_passengers_dsb2019/submissions/submission_000000670 ...
CV fold 0
        score   rmse       time
        train  0.095  26.625145
        valid  0.275  15.903654
        test   0.275   4.837199
```
> Moreover, the main process dump the log to the disk anyway so it should not increase that much the need for I/O.

The difference is that piping directly for multiple files and writing one line at at time is random disk access (with up to [10ms latency penalty](http://panthema.net/2019/0322-nvme-batched-block-access-speed/storage-performance-08.png) per file change on HDD), if several submissions are running, while writing a file in full is sequential access. Presumably some of it is cached but still, if you have a server with 32 workers, it can add up.

> The main issue with the buffer size solution is that we do not solve the problem, we only push it farther away. It means that it is easy to deadlock the server by simply submitting multiple submission that will do a lot of printing.

It's possible to deadlock a worker yes, not the server. Still if the buffer size is high enough (e.g. 100MB) means that you are doing something internationally bad (that's a log of 1.2M lines), and in this unlikely case, the timeout will kill the sleeping processes eventually.

In any case, someone should make a PR, even if it's piping to files. I guess one can always create that temporary folder in /dev/shm tmpfs as a workaround for I/O concerns.

**Comment by glemaitre** [comment]
Now that I am looking again at the log, I see that I already saw we had an issue: https://github.com/paris-saclay-cds/ramp-board/pull/254

Let's implement the best solution here.

**Comment by glemaitre** [comment]
One thing that I am thinking about is to filter warning when we run solutions.

**Comment by agramfort** [comment]
@glemaitre what is the best solution?

**Comment by glemaitre** [comment]
Apparently there is no best solution. But we have to be pragmatic and I think that we can give a try to log into a file, limiting whatever will not be useful (warning, catching the printing from within the submission file). We could also monitor the size of the log to detect automatically thing are weird.

**Comment by kegl** [comment]
+1 for logging into a file. Also good for checking history if needed.
