### ISSUE TITLE
toggle submissions in and out of competition

### ISSUE THREAD

**Issue by kegl** [paris-saclay-cds/ramp-board#288]
This is a crucial functionality for competitive RAMPs, this is the way for a participant to select a particular submission to participate in the competition. The button was kept in the frontend but the view function was missing in this new version of the code. 

It is added back in this commit: https://github.com/paris-saclay-cds/ramp-board/pull/276/commits/63d39202c8486a79eb29d6b50bb5cba5abb031ab

The issue can be closed when the https://github.com/paris-saclay-cds/ramp-board/tree/acrobot_dev branch is merged into master.

cc @tomMoral @agramfort if you use this feature in the data camp

**Comment by agramfort** [comment]
yes we saw this too. I attempted a fix
https://github.com/paris-saclay-cds/ramp-board/pull/278 but have no time to
pursue.

>

**Comment by kegl** [comment]
I think your fix is more about this issue isn't it? https://github.com/paris-saclay-cds/ramp-board/issues/289
