### ISSUE TITLE
ENH Improve log messages

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#291]
When running the frontend, there is a bunch of logs of the form,
```
You need to wait 444 more seconds until next submission
You need to wait 190 more seconds until next submission
You need to wait 521 more seconds until next submission
You need to wait 54 more seconds until next submission
No access to sandbox for event air_passengers_dsb2019. If you have already signed up, please wait for approval.
No access to sandbox for event air_passengers_dsb2019. If you have already signed up, please wait for approval.
No access to my submissions for event air_passengers_dsb2019. If you have already signed up, please wait for approval.
```
presumably this is the message the user sees, but for logging it would be useful to also include a date and the user who experienced it.

**Comment by glemaitre** [comment]
I think that this is an issue with configuring properly the flask logger:
https://flask.palletsprojects.com/en/1.1.x/logging/

If we could do that throught the config file it could be perfect
