### ISSUE TITLE
scoring bug

### ISSUE THREAD

**Issue by kegl** [paris-saclay-cds/ramp-board#292]
Fold predictions and scores are scrambled. We assume here 
https://github.com/paris-saclay-cds/ramp-board/blob/master/ramp-database/ramp_database/tools/submission.py#L632
that folds are always enumerated in the same order but they seem not to be. It is also possible that the problem is when the folds are created here: https://github.com/paris-saclay-cds/ramp-board/blob/master/ramp-database/ramp_database/tools/submission.py#L95

In any case, a lot of times the scores are assigned to wrong folds. It seems to be not affecting the leaderboard scores, only the combined score, but I am not sure. If they do, it's a quite serious bug.

**Comment by rth** [comment]
> We assume here
https://github.com/paris-saclay-cds/ramp-board/blob/master/ramp-database/ramp_database/tools/submission.py#L632
that folds are always enumerated in the same order but they seem not to be. 

Yes, from the postgresql docs, https://www.postgresql.org/docs/9.1/queries-order.html

> If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on.

So one would need to add a `sort` by id to be sure. Though I'm not sure what impact that would have on existing RAMP deployments.

**Comment by kegl** [comment]
Thanks! 

We moved away from the DB when blending (using rampwf's blender) in this commit https://github.com/paris-saclay-cds/ramp-board/pull/276/commits/91522cd43d4827bd38b2d607b6fff9503dd3e21f and it seems that we don't use the folds from the DB anywhere else, but I would keep this issue open till we get rid of the folds in the DB.
