### ISSUE TITLE
Update frontend index page

### ISSUE THREAD

**Issue by lucyleeow** [paris-saclay-cds/ramp-board#331]
Update the home page (`index.html`), especially for the new OVH server:

As discussed with @glemaitre and @agramfort;
- remove CDS/Paris Saclay specific things. If ramp board is intended to be a package used by others to setup their own server, the home page should be more general instead of looking like it is only for CDS
- make it clear that ramp board is both a bundle of packages that allow you to setup your own server and a platform for ML challenges

Is this an accurate summary of our discussion? What do you think @kegl?

**Comment by agramfort** [comment]
let's have section at the bottom that can be configured and that says that
RAMP is developed by CDS
and than hosted and sponsored by OVH

**Comment by kegl** [comment]
I agree: we should keep CDS as the originator of the package.
