### ISSUE TITLE
Inconsistent text size in the front-end

### ISSUE THREAD

**Issue by DjalelBBZ** [paris-saclay-cds/ramp-board#346]
Hey guys,

Pulled the latest RAMP from the master branch and noticed the text size changed drastically. Almost everything is basically bigger (probably way too big). 

![image](https://user-images.githubusercontent.com/703753/72280160-f7fee600-3637-11ea-84e7-4e477319c89a.png)

Am I the only one noticing?

**Comment by agramfort** [comment]
yes indeed

it's currently looked into by @lucyleeow

>

**Comment by lucyleeow** [comment]
Addressed in #344 - waiting for review and merge.

**Comment by glemaitre** [comment]
Closing then. Let's open new issues if there are some remaining visual glitches.
