### ISSUE TITLE
Issue with power_by

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#368]
Looking at the documentation, I think that the `power_by` feature is actually impossible to put in practice. Indeed, we specify to put the file into a folder assuming that users will installed from source in dev mode. I hope that people could only use `pip` and it will be a nightmare to tell them where to look into the disk to paste the image. I would remove from the documentation this feature and just keep it as it is for our server.

ping @agramfort @maikia

**Comment by agramfort** [comment]
shall we make it a config parameter where the power by folder is?

>

**Comment by glemaitre** [comment]
It is a possibility but not sure where to add this feature.

**Comment by glemaitre** [comment]
It is a blocker because you cannot install from PyPI

**Comment by glemaitre** [comment]
I solved this issue
