### ISSUE TITLE
Suspicous change in bag public scores

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#378]
The bag public score for air_passenges changed significantly for air_passengers with the starting kit after I updated ramp-board and ramp-workflow to the latest version (from 0.77 to 0.29, see below);

![Screenshot_2020-01-31 Leaderboards - RAMP(1)](https://user-images.githubusercontent.com/630936/73558093-c452f700-4452-11ea-9fa4-db9821efe9a8.png)

Possibly related to https://github.com/paris-saclay-cds/ramp-board/issues/106 (or some related issue)

cc @glemaitre

**Comment by rth** [comment]
The logs for this submission are,
```
^[[38;5;178m^[[1mTesting Number of air passengers prediction^[[0m
^[[38;5;178m^[[1mReading train and test files from ramp_deployment/ramp-data/air_passengers/data ...^[[0m
^[[38;5;178m^[[1mReading cv ...^[[0m
^[[38;5;178m^[[1mTraining ramp_deployment/events/air_passengers_mosef2019/submissions/submission_000000703 ...^[[0m
^[[38;5;178m^[[1mCV fold 0^[[0m
        ^[[38;5;178m^[[1mscore   rmse      time^[[0m
        ^[[38;5;10m^[[1mtrain^[[0m  ^[[38;5;10m^[[1m0.313^[[0m  ^[[38;5;150m2.281577^[[0m
        ^[[38;5;12m^[[1mvalid^[[0m  ^[[38;5;12m^[[1m0.314^[[0m  ^[[38;5;105m0.392726^[[0m
        ^[[38;5;1m^[[1mtest^[[0m   ^[[38;5;1m^[[1m0.818^[[0m  ^[[38;5;218m0.152233^[[0m
^[[38;5;178m^[[1mCV fold 1^[[0m
        ^[[38;5;178m^[[1mscore   rmse      time^[[0m
        ^[[38;5;10m^[[1mtrain^[[0m  ^[[38;5;10m^[[1m0.318^[[0m  ^[[38;5;150m2.183925^[[0m
        ^[[38;5;12m^[[1mvalid^[[0m  ^[[38;5;12m^[[1m0.314^[[0m  ^[[38;5;105m0.387053^[[0m
        ^[[38;5;1m^[[1mtest^[[0m   ^[[38;5;1m^[[1m0.818^[[0m  ^[[38;5;218m0.151364^[[0m
^[[38;5;178m^[[1mCV fold 2^[[0m
        ^[[38;5;178m^[[1mscore   rmse      time^[[0m
        ^[[38;5;10m^[[1mtrain^[[0m  ^[[38;5;10m^[[1m0.313^[[0m  ^[[38;5;150m2.140815^[[0m
        ^[[38;5;12m^[[1mvalid^[[0m  ^[[38;5;12m^[[1m0.316^[[0m  ^[[38;5;105m0.387750^[[0m
        ^[[38;5;1m^[[1mtest^[[0m   ^[[38;5;1m^[[1m0.814^[[0m  ^[[38;5;218m0.152026^[[0m
^[[38;5;178m^[[1mCV fold 3^[[0m
        ^[[38;5;178m^[[1mscore   rmse      time^[[0m
        ^[[38;5;10m^[[1mtrain^[[0m  ^[[38;5;10m^[[1m0.317^[[0m  ^[[38;5;150m2.148498^[[0m
        ^[[38;5;12m^[[1mvalid^[[0m  ^[[38;5;12m^[[1m0.314^[[0m  ^[[38;5;105m0.383341^[[0m
        ^[[38;5;1m^[[1mtest^[[0m   ^[[38;5;1m^[[1m0.814^[[0m  ^[[38;5;218m0.151112^[[0m
^[[38;5;178m^[[1mCV fold 4^[[0m
        ^[[38;5;178m^[[1mscore   rmse      time^[[0m
        ^[[38;5;10m^[[1mtrain^[[0m  ^[[38;5;10m^[[1m0.315^[[0m  ^[[38;5;150m2.225629^[[0m
        ^[[38;5;12m^[[1mvalid^[[0m  ^[[38;5;12m^[[1m0.316^[[0m  ^[[38;5;105m0.383677^[[0m
        ^[[38;5;1m^[[1mtest^[[0m   ^[[38;5;1m^[[1m0.814^[[0m  ^[[38;5;218m0.152310^[[0m
```

we need to do something about colors in the log BTW. 

As far as I can tell the RMSE in train is larger than in validation is test, which is certainly not ideal ^^

**Comment by glemaitre** [comment]
So this seems in line with what is reported on by ramp-workflow:

train -> ~0.3; valid -> ~0.3, test -> 0.8

**Comment by glemaitre** [comment]
is it the same kit than before

**Comment by rth** [comment]
You are right, I misread the logs. So this look in the right order, but the question is what changed for the validation score. Will try to investigate.

**Comment by glemaitre** [comment]
The only change is here:
https://github.com/paris-saclay-cds/ramp-workflow/commit/b776d9759b47ca91b77dcc8a3accd3a31c7be6ab

**Comment by rth** [comment]
Indeed but there is also the pandas 1.0 to work with latest ramp-workflow, which could have some unexpected side effects I imagine.

**Comment by rth** [comment]
I can confirm that https://github.com/paris-saclay-cds/ramp-workflow/commit/add3fdc4cd6afd1c42811616b1e10b7fed9be503 fixes this. Thanks @glemaitre !
