### ISSUE TITLE
Log for failed submissions no longer accessible in frontend

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#381]
It looks like in latest ramp-board versions users can no longer see the log for failed submissions in the frontend. The link to the log simply no longer exists.

I'm not sure if it's intentional (e.g. for security reasons), but it's still a bit problematic as it means users now have no idea why their submission failed.

**Comment by glemaitre** [comment]
No this is a bug indeed. I might have introduced this when logging in files?

**Comment by glemaitre** [comment]
Good new is that it is accessible:

```
https://dev.ramp.studio/hash_submission/error.txt
```

But we removed the `<a href>` link on the page. We should revert that.

**Comment by glemaitre** [comment]
So basically it should when we create the failed leaderboard. It should quite easy.

**Comment by glemaitre** [comment]
Found the bug and make a bug fix release on PyPI.

**Comment by glemaitre** [comment]
Forgot to restart the dispatcher. It works.
