### ISSUE TITLE
Remove combine score in problems.html and problem.html

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#387]
Since we currently don't compute the combined score, it would be best to inject the best competition score in the problem/problems.html page instead of having (combined score=None)

**Comment by agramfort** [comment]
agreed. It's weird to display something we don't support

>

**Comment by glemaitre** [comment]
We should also check for the keywords as well. I don't remember if I removed the option to add some or it is just that I don't remember how to add them.
