### ISSUE TITLE
Change link from GitHub to something else in the ramp-problem

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#393]
While I solved the issue to get the starting kit directly from the server, we still have a link that point to github: https://dev.ramp.studio/problems/iris

It refers to the problem. A possible solution is to pack an archive when creating the problem initially and to make it downloadable as well.

Another solution is to remove the link directly and make it downloadable only for events.

ping @agramfort any thoughts?

**Comment by agramfort** [comment]
this page https://dev.ramp.studio/problems/iris also contains a version of
the notebook. Can we download the kit version that matches this notebook?

>

**Comment by glemaitre** [comment]
Yep this will be the last zip file indeed




Sent from my phone - sorry to be brief and potential misspell.

**Comment by glemaitre** [comment]
Fixed in master.
