### ISSUE TITLE
Issue with external data symlink

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#409]
When introducing the changes from @tomMoral (not to blame because it was not tested :)), I did not pay attention and we introduce a big regression.

When a user sign-up to an event we make a copy of the starting kit and submit it (for setting up the sandbox). If the external data were inside, we copied this file. Now with the symlink, we synlink to the starting kit and at every submission, we symlink the external data to this first submission data which symlink to the starting-kit external data.

Now when a user upload a file, it will be copied in place of the external data of the original kit where all the submissions are pointing to.

So the resolution is to make a hard-copy of the original external data when submitting the starting-kit. When uploading the data, we should replace the first submission and not the original data. We can check the diff on the `ramp.studio` server in production where I programmed this way in the past (including a parameter `hard_copy=True` for the original submission).

Be aware that this way one cannot download the external data from a previous submission because it will only be representative of the last submission uploaded.

**Comment by rth** [comment]
Thanks for the report! Which PR is this referring to? I would like to sync with master on my deployed instance, and I'm not sure if I'm currently affected by this (ramp_board as of Thu Jan 30, 2020).

The current logs look reasonable in any case, e.g.
```
Copying ramp_deployment/events/air_passengers_mosef2019/submissions/submission_000000734/external_data.csv to ramp_deployment/events/air_passengers_mosef2019/submissions/submission_000000689/external_data.csv
``` 

> So the resolution is to make a hard-copy of the original external data when submitting the starting-kit. When uploading the data, we should replace the first submission and not the original data. We can check the diff on the ramp.studio server in production where I programmed this way in the past (including a parameter hard_copy=True for the original submission).

Not sure I understood the solution. Could you paste the diff please, if it's already available?

**Comment by glemaitre** [comment]
> Which PR is this referring to?

no PR just a bug that I got on saturday.

**Comment by glemaitre** [comment]
look at all the symlink to in the submission folder. you will see that they point to the original submission and the original submission will point to the starting kit (which is worng)

**Comment by glemaitre** [comment]
So we need:

* add a parameter `hard_copy` to `add_submission` -> https://github.com/paris-saclay-cds/ramp-board/blob/master/ramp-database/ramp_database/tools/submission.py#L41. If `hard_copy` then make a copy instead of a symlink.
* Here (https://github.com/paris-saclay-cds/ramp-board/blob/master/ramp-database/ramp_database/tools/team.py#L68) we should make a hard_copy.
* Else where we should make symlink
* Then make sure when we upload, we overwrite the external_data in the first submission.

**Comment by rth** [comment]
Thanks for the explanations @glemaitre ! will try to propose a PR.
