### ISSUE TITLE
Implement user rejection 

### ISSUE THREAD

**Issue by aboucaud** [paris-saclay-cds/ramp-board#41]
Currently there are only three possible `access_level` for RAMP users : `asked`, `user` and `admin`.

Because of SPAM users that are not accepted, the list of pending users piles up and it is difficult to make a selection on new users, except being very fast to click on email notifications.

I think it's important to implement

- [ ] a new access level `rejected` in the db_model (maybe more)
- [ ] accessors and modifiers in the `db_tools`
- [ ] the linked options and buttons on the frontend
- [ ] possibly add the date of sign up next to the users in the  `approve_users` page to help cleaning very old entries

**Comment by glemaitre** [comment]
We can now remove the users from the list
