### ISSUE TITLE
BUG non-ASCII not allowed in submission

### ISSUE THREAD

**Issue by lucyleeow** [paris-saclay-cds/ramp-board#419]
Submitting starting kits which contain non-ASCII characters gives error. E.g. in the Brevet example, column names include non-ASCII characters, thus the `estimator.py` file contains non-ASCII characters. When submitting you get this error: `Error: ‘ascii’ codec can’t encode character ‘\xe9’ in position 518: ordinal not in range(128)`

Brevet works fine locally with `ramp-test`

**Comment by rth** [comment]
Could you find the full error traceback in the logs?

**Comment by lucyleeow** [comment]
Could you explain how to do this?
(aside - you have access to the server now right?)

**Comment by rth** [comment]
In the deployment folder on the server, there should be a folder `<deployment-dir>/events/<event-name>/logs`, with the submission logs. But in this case for Brevet event it's empty, maybe traceback from failed submissions is not stored I'm not sure.  (yes, I have access to the sever).

In any case the finding the full traceback would be useful to investigate...

**Comment by lucyleeow** [comment]
`ramp_deployment/events/brevet_studentkit` just has
```
drwxrwxr-x  3 ramp ramp 4096 Mar 18 11:21 ./
drwxrwxr-x 13 ramp ramp 4096 Mar 18 11:17 ../
-rw-rw-r--  1 ramp ramp 1014 Mar 18 10:15 config.yml
drwxrwxr-x  3 ramp ramp 4096 Mar 18 12:28 submissions/
```
no logs dir? I'm not familiar with the server at all (was amazed to deploy event) - so might not be doing it right?

**Comment by rth** [comment]
> no logs dir?

Yes, exactly. That's where I would have looked, and it's there for other events. So 
> maybe traceback from failed submissions is not stored I'm not sure.

**Comment by lucyleeow** [comment]
Hmm I very quickly get the error message pop up so maybe there is some kind of check before the submission actually starts running.

**Comment by agramfort** [comment]
I suspect it's an html / js / flask issue.

>
