### ISSUE TITLE
Submissions code is visible by default for event participants

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#422]
It looks like submissions code in the Leaderboard is accessible by default for all participants: I.e. they can click on the submission name and get to the code.

Previously I though only an admin could do it. Not sure if it's related to an event being "competitive". Under "Update Event" it says,

> Check if the event is competitive. In competitive events users may dedicate the submission with which they would like to enter in the competition. It is not mandatory: if there is no dedicated submission, the best one according to the public leaderboard score will enter in the competition. 

In any case selecting or not that checkbox doesn't have an effect: the code is always visible.

That's probably not ideal, particularly for teaching events.

**Comment by agramfort** [comment]
I think it's because the open date is 2000-01-01 00:00:00 in your
event. Can you change the date and see if it works?

**Comment by rth** [comment]
Yes, you are right, forgot about that, thanks! It had
```
The links to submission codes will come alive at this time, 
signaling the start of the collaborative phase.
public opening timestamp (UTC)  2000-01-01 00:00:00
```

I think we should set it to 2100 by default, same as closing timestamp.

**Comment by rth** [comment]
(and I can confirm that changing the date in the future removes the visibility of submission links)

**Comment by agramfort** [comment]
close then?

>

**Comment by rth** [comment]
I was saying that maybe by default submission code should be hidden (unless explicitly made visible by event admin)? So I would propose to change the default date for "public opening timestamp". The current situation is somewhat unexpected and as an admin, one has no warning this is happening.

**Comment by rth** [comment]
Or if we keep this default, docs at https://paris-saclay-cds.github.io/ramp-docs/ramp-board/stable/create_ramp_event.html should be updated IMO.

**Comment by agramfort** [comment]
if we make default choice for opening data (like in one month) I fear this
will become open
without notice. Maybe we can enforce the specification of an open date when
creating the event
to avoid issues?

>

**Comment by rth** [comment]
> if we make default choice for opening data (like in one month) I fear this
will become open
without notice. 

Note that "opening" date and "public opening" date are 2 separate fields. Currently the defaults seem to be,
```
opening timestamp (UTC)  2000-01-01 00:00:00
public opening timestamp (UTC)  2000-01-01 00:00:00
closing timestamp (UTC)  2100-01-01 00:00:00
```
i.e. events are open with submissions visible to participants and closed in 2100.

To be more specific I would propose to change this to,
```
opening timestamp (UTC)  2000-01-01 00:00:00
public opening timestamp (UTC)  2100-01-01 00:00:00
closing timestamp (UTC)  2100-01-01 00:00:00
```
i.e. events are open by default with submissions hidden from participants until 2100 and event will close in 2100. There shouldn't be an issue with something happening without notice with these default unless I'm missing something?

> Maybe we can enforce the specification of an open date when
creating the event to avoid issues?

We could, but it would be good to have safer defaults as well.

**Comment by agramfort** [comment]
sounds beautifully simple !

+1 for this

>
