### ISSUE TITLE
Travis CI credit limit reached

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#459]
As mentioned by @lucyleeow in https://github.com/paris-saclay-cds/ramp-board/pull/455#issuecomment-723344504

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

Also related scikit-learn thread: https://mail.python.org/pipermail/scikit-learn/2020-November/003900.html

That was fast, we used the initial credit allocation in just a few days.

What do you think we should do?  Ask for more credit (and if so how much?) or try to migrate to another CI (e.g. Github actions)?

cc @agramfort

**Comment by agramfort** [comment]
I would move to github actions but it's some work :'(

>
