### ISSUE TITLE
Auto-format code with black 

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#523]
It might be a good idea to apply [black](https://pypi.org/project/black/) on the code base, to think less about formatting. This can  also be included in the pre-commit setup to auto-format on each commit.

There aren't many open PR where this would be an issue.

flake8 config would then need to be [adjusted slightly](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8), and the check would need to be added to CI.

**Comment by agramfort** [comment]
No strong feeling

**Comment by kegl** [comment]
I was fine with it till I saw it will replace all single quotes with double. If that can be configured, I'm fine with it.

**Comment by rth** [comment]
> I was fine with it till I saw it will replace all single quotes with double. If that can be configured, I'm fine with it.

The idea of black is have mostly 0 configuration, so that users think less about formatting. So double vs simple quotes cannot be configured.

**Comment by rth** [comment]
An example of how code would look is in #540 . @kegl are single quotes still a blocker?
