### ISSUE TITLE
Missing error traceback when a submission failed

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#575]
In the past, we were providing the traceback with the log when a submission was failing.
Someone could investigate the issue:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/7454015/169645129-15fd6a00-9749-4c32-a153-417ee74d2222.png">

Now, there are no hyperlinks with the `training_error`.
@rth @agramfort do you know if we change this?

**Comment by agramfort** [comment]
this should not happen

**Comment by glemaitre** [comment]
Solved in #576 (and with a non-regression test ;))
