### ISSUE TITLE
RAMP: Documentation

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#95]
Each of the packages should create is own documentation. We should at least get the API reference right since that we will have the docstring.

- [x] Add CI to build the documentation at each PR (circle ci to get the artifacts)
- [x] Add the install, tests instructions
- [x] Add how to setup a server
- [x] Add how to deploy a ramp event
- [x] Add a note about the ramp workers
- [x] Add a documentation how to implement a new type of worker
- [x] Add the API documentation for all the packages
- [x] Fill up whatever remaining page

**Comment by rth** [comment]
Nice work on the documentation!

Just went through re-installation of ramp_board to get the latest version and it went rather smoothly thanks to it. The manual folder layout is also a nice improvement (at least I now understand better what is going on).

**Comment by glemaitre** [comment]
Thanks. We are going to add a couple of documentation sections regarding the structure of a ramp-kits and ramp-data as well.

@rth you can cherry pick https://github.com/paris-saclay-cds/ramp-board/pull/233 for the reset of the password. This is actually working and could be useful for your next class just in case.
