### ISSUE TITLE
RAMP: Rename packages

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-board#97]
We need to rename all packages in this bundle:

* `databoard` will only contain frontend (website) tools, I am proposing `ramp-website` then.
* `ramp-database` is already good.
* `ramp-engine` is a not a good name. It contains the dispatcher and the workers implementations. Therefore I am thinking in `ramp-launcher`.
* `ramp-workflow` should be renamed into `ramp-sdk`.
* the current directory should be renamed from `ramp-board` to `ramp`. We have to check the name collision is actually an issue.

**Comment by kegl** [comment]
I would use ramp-trainer, since it's more specific. Even though it's train/(valid)test/score/blend, trainer gives me a better idea of what it does.

**Comment by glemaitre** [comment]
I am a big fan of `trainer` because the scheduler and workers are "somehow" agnostic of what happens when launching a submission. The naming would require to be quite general then.

**Comment by kegl** [comment]
You mean _not_ a big fan :). I would name it trainer for the exact reason you are not a big fan: it's a generic techno but we intend to use it for training ML models, so naming is the only way to express that. You don't want to give the scope artificially large cause the issues coming with people using it for something else will multiply exponentially.

**Comment by glemaitre** [comment]
We can reopen the issue if the naming is not good enough. But at least the imports are consistent.
